<div id="progress-bar-container">
    <div id="progress-bar"></div>
</div>
<script>
    require(['jquery'], function ($) {
        $(document).ready(function () {
            var progressBar = $('#progress-bar');
            var progressBarContainer = $('#progress-bar-container');

            function updateProgressBar() {
                $.ajax({
                    url: '<?php echo $block->getUrl('module/index/progress'); ?>',
                    method: 'GET',
                    success: function (response) {
                        progressBar.css('width', response.progress + '%');
                    }
                });
            }

            updateProgressBar();

            setInterval(function () {
                updateProgressBar();
            }, 5000); // Refresh the progress bar every 5 seconds
        });
    });
</script>
