<?php
    /** @var \Magento\Customer\Block\Form\Login $block */
?>

<div id="popup-login">
    <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Form\Login')->setTemplate('Magento_Customer::form/login.phtml')->toHtml(); ?>
</div>

<script>
    require(['jquery', 'Magento_Ui/js/modal/modal'], function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __('Login'); ?>',
            buttons: [{
                text: $.mage.__('Close'),
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#popup-login'));

        $('#login-link').click(function() {
            $('#popup-login').modal('openModal');
        });
    });
</script>
