<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?= $block->getChildHtml() ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);?>
<script>
require(['jquery'], function ($) {
    $(document).ready(function () {
        var typingTimer;
        var doneTypingInterval = 5000; // 1 second

        $('#email_address').on('input', function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(validateEmail, doneTypingInterval);
        });

        function validateEmail() {
            var email = $('#email_address').val();
            var ajaxURL = '<?php echo $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB); ?>';
            // Remove existing error message
            $('#email-error').remove();
            // Make an AJAX request to check if the email already exists
            $.ajax({
                url: ajaxURL + 'customer/checkemail/validate',
                data: {email_check: email},
                type: 'post',
                dataType: 'json',
                success: function (response) {
                    if (response.error) {
                        $('#email_address').after('<div id="email-error" style="color: red;">' + response.message + '</div>');
                    }
                }
            });
        }
    });
});
</script>
