<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <body >

   <div class="bg">

        <h1 style="color:green:">Thank you for trusting Cicclo</h1>
        <p>We received your loan request, we'll be in touch shortly!</p>
        <p>Please prepare the documents needed. These includes your identification. </p>
        <ul class="proof"><h2> Valid IDS </h2>
        <li>Birth Certificate</li>
            <li>Driver's License</li>
            <li>Secondary IDS</li>

        </ul>
        <ul class="proof"><h2> Proof of billing</h2>
            <li>Electric Bill</li>
            <li>Water Bill</li>
            <li>Internet Bill</li>
        </ul>
        <ul class="proof"><h2>Downpayment</h2>
            <li>10%</li>
            <li>20%</li>
            <li>30%</li>
            <li>40%</li>
            <li>50%</li>
        </ul>
        </div>
        <script type="text/javascript">
            require(['jquery'], function($) {
                // Disable the back button
                window.history.pushState(null, '', document.URL);
                window.addEventListener('popstate', function() {
                    window.history.pushState(null, '', document.URL);
                });
            });
        </script>
    </body>
</html>
